# Configuración de Azure Event Hubs con Kafka Client
kafka.bootstrap.servers=poc-quarkus-eventhubs-tf.servicebus.windows.net:9093
# Protocolo y Mecanismo de Autenticación
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=OAUTHBEARER
# Nota: Sin espacio antes del punto y coma
kafka.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
kafka.sasl.login.callback.handler.class=com.nttdata.AzureKafkaCallbackHandler       
azure.client.id=
azure.client.secret=
azure.tenant.id=
kafka.group.id=quarkus-consumer-group
kafka.key.serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.value.serializer=org.apache.kafka.common.serialization.StringSerializer       
kafka.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer     
kafka.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer 